defaults: &defaults
  adapter: sqlite3
  encoding: utf8

development:
  database: db/tecfiler-rails_development.db
  <<: *defaults

#test:
#  database: db/tecfiler-rails_test.db
#  <<: *defaults

test: &test  
  database: ":memory:"
  <<: *defaults

production:
  database: db/tecfiler-rails_production.db
  <<: *defaults
